apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: blog

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 10.0.171.239
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127

---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: prod
spec:
  type: ExternalName
  externalName: blog.info